version: "3.3"
services:
  practice_db:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pass
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_config:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json
    ports:
      - 5050:80
volumes:
  db_data:
  pgadmin_config: